// Generated by CoffeeScript 1.10.0
(function() {
  var Compiler, JadeCompiler, fs, jade,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  fs = require('fs');

  jade = require('jade');

  Compiler = require('metaserve/lib/compiler');

  JadeCompiler = (function(superClass) {
    extend(JadeCompiler, superClass);

    function JadeCompiler() {
      return JadeCompiler.__super__.constructor.apply(this, arguments);
    }

    JadeCompiler.prototype.default_options = {
      base_dir: './views',
      ext: 'jade'
    };

    JadeCompiler.prototype.compile = function(jade_filename, cb) {
      var options;
      options = this.options;
      return fs.readFile(jade_filename, function(err, file_str) {
        return cb(err, {
          content_type: 'text/html',
          source: file_str,
          compiled: jade.compile(file_str, {
            filename: options.base_dir + '/_.jade'
          })()
        });
      });
    };

    return JadeCompiler;

  })(Compiler);

  module.exports = function(options) {
    if (options == null) {
      options = {};
    }
    return new JadeCompiler().set(options);
  };

}).call(this);
