// Generated by CoffeeScript 1.12.4
(function() {
  var VERBOSE, fs, jade, path;

  fs = require('fs');

  jade = require('jade');

  path = require('path');

  VERBOSE = process.env.METASERVE_VERBOSE != null;

  module.exports = {
    ext: 'jade',
    default_config: {
      content_type: 'text/html'
    },
    compile: function(filename, config, context, cb) {
      if (VERBOSE) {
        console.log('[JadeCompiler.compile]', filename, config);
      }
      return fs.readFile(filename, function(err, file_str) {
        var html, jade_compiler;
        filename = path.join(config.base_dir, '_.jade');
        jade_compiler = jade.compile(file_str, {
          filename: filename
        });
        html = jade_compiler(context);
        return cb(err, {
          content_type: config.content_type,
          source: file_str,
          compiled: html
        });
      });
    }
  };

}).call(this);
